swagger: "2.0"
info:
  title: "Example API"
  description: "Base API Template"
  version: "1.0.0"
host: localhost:9001
schemes:
  - "http"
consumes:
  - application/json
produces:
  - application/json